### ISSUE TITLE
Error stream quality best?

### ISSUE THREAD

**Issue by Gimpoid** [beaston02/MFCRecorder#18] opened 2017-09-10 13:45 UTC
Actually I noticed I was running an older version doesnt seem to appear in the new version.

**Comment by beaston02** [comment] 2017-09-10 14:03
What's happening (from what I can tell) is MFC is reporting the model as in a free chat, but the models cam is not broadcasting. I've actually already made changes to silence this error, so it will be fixed in the next update  because it doesn't change anything other than the logged output, I didn't bother updating the script just for that.

**Closed** 2017-09-10 14:03 UTC

**Comment by beaston02** [comment] 2017-09-10 14:06
Lol. I see you updated and closed this as I was posting a response. 

It will still show this error in the current version, but it's only happening when MFC is reporting incorrectly, or the model is having trouble with their cam, or whatever the actual root cause is. You're not seeing it now only because there isn't a model on your wanted list that's causing the issue at the moment.
