### ISSUE TITLE
configparser.NoSectionError: No section: 'paths'

### ISSUE THREAD

**Issue by rikardote** [beaston02/MFCRecorder#16] opened 2017-09-05 02:54 UTC
On Linux & MacOs

get this error running MFCRecorder.py

Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MFCRecorder.py", line 17, in <module>
    save_directory = Config.get('paths', 'save_directory')
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'paths'

**Comment by beaston02** [comment] 2017-09-05 02:58
Are you running the script for the first time, or have you used it before and just updated?

I believe this error generally happens when the configure file isn't in the same directory as the main script (MFCRecorder.py in this case). Is the config.conf file in fact in the same directory as the MFCRecorder file, and have you configured the config file for your needs?

**Comment by rikardote** [comment] 2017-09-05 03:15
yes same directory, only the wanted.txt is on different directory, and i already configured the paths on config.conf file

**Comment by beaston02** [comment] 2017-09-05 03:29
Have you ran this script before and this is a new error with the last update? 

I did change how the path is passed to the script because I was noticing one of my systems wasn't liking the old way, but all that I tested on (Mac, couple of flavored of Linux, and BSD) all seemed to be fine wit this new method. 

I'm replying from my phone, so I unfortunately won't have great details or instructions, but if you wanted to look at one of the older scripts (prior to today should all have the "old method") and copy/paste it replacing the new method and see if it works. The line will start with "Config.read(" I believe. It should be towards the top of the file not long after all the "import..." and "from.... Import..." lines. 

Another option to test would be to enter the actual path to the config in that line. That would mean changing it to "Config.read("/complete/path/to/the/config.conf")" (excluding the outside quotes, but including them around the path) and see if that works.  

Again, sorry for the not-so-great response.

**Comment by rikardote** [comment] 2017-09-05 15:34
it works now. i have to harcoded all the paths and remove this part from the MFCRecorder.py script:

```
if not os.path.exists(os.path.dirname(sys.argv[0]) + "/static/avatars/{}.jpg".format(model['uid'])):
            try:
                response = requests.get(model['avatar'])
                if response.status_code == 200:
                    with open(os.path.dirname(sys.argv[0]) + "/static/avatars/{}.jpg".format(model['uid']), 'wb') as f:
                        f.write(response.content)
            except (requests.exceptions.ConnectionError, requests.exceptions.MissingSchema):pass
```

**Comment by beaston02** [comment] 2017-09-05 16:02
Thanks for the update. That is interesting you're having this issue. I have no idea what might be causing it. The portion I would think was causing the problem ( the "os.path.dirname(sys.argv[0])" line) is also used in other parts of the script (like getting the online models). So I guess it wasn't the issue. 

either way, I'm glad you've got it working! You can manually download the models avatars to the "avatar" directory and name them with the models UID if you care enough to have them show.

**Comment by rikardote** [comment] 2017-09-05 16:11
i remove and harcode all the "os.path.dirname(sys.argv[0])" lines from the script. 

which distribution of linux do you use? 

i'm using xubuntu 16.04

**Comment by beaston02** [comment] 2017-09-05 16:19
I believe I was running on Debian 7 and Ubuntu 14, but it's been so long since I set it up, I can't remember. I also ran it on my Mac with no issues. 

I'm replying from my phone, so excuse me for lack of actual lines, or even line numbers, but you could pull up the old scripts (again, anything prior to about September 3rd) and you will see a different method for getting the path (it was storing the model.pickle file to the directory I ran the script from instead of in the MFCRecorder directory). You could replace the "OS.path.dirname(sys.....)" with the old method and see if that changes anything? 

Otherwise, I'll do some more testing and see if I can't reproduce the issue.

**Comment by longsack** [comment] 2017-09-05 19:59
![capture](https://user-images.githubusercontent.com/31635078/30080874-c99ae36a-924a-11e7-9214-f83027084c86.PNG)
I believe I'm having the same issue.  First time user, just set it up... On Ubuntu 14.  Thoughts?

**Comment by beaston02** [comment] 2017-09-05 23:49
@longsack - Sorry for the slow reply. I was just working on this issue and didnt see your post until I came here to get the exact error. Im about to post an update now. If either of you wouldnt mind testing it, I would really appreciate it. 

I just tested it (the current one which you two are having issues with) again on my ubuntu server (running 14.04.4), and it is working fine on there. Please let me know if the new script works for you.

**Comment by rikardote** [comment] 2017-09-05 23:55
@beaston02 -  i test the update and it work great.

**Comment by beaston02** [comment] 2017-09-05 23:58
@rikardote Thats great to hear! Thank you for reporting back so quickly. 

Im going to leave this open still to see if @longsack reports back. 

Thanks again for reporting, your patience, and for helping me figure this out.

**Comment by beaston02** [comment] 2017-09-05 23:59
@rikardote is the avatar images downloading for you now also?

**Comment by rikardote** [comment] 2017-09-06 01:42
@beaston02 - yes it is working too

**Comment by longsack** [comment] 2017-09-06 01:52
little further now... but still issues... i'm new, sorry! :)

no module named '_curses' seems to be the error when calling getModels.py

looking to see what I can do via the google web.

**Comment by beaston02** [comment] 2017-09-06 01:57
@longsack, do you have the latest getModels.py? I believe curses was part of blessings, which I removed in the latest update (caused issues on windows systems). 

Also, are did you install the requirements? I did switch to a new library for logging calored text which may use curses also. I believe I added it to the requirements file.

**Comment by longsack** [comment] 2017-09-06 02:01
![capture1](https://user-images.githubusercontent.com/31635078/30091109-5612d424-927d-11e7-8c25-e3983da10672.PNG)

**Comment by beaston02** [comment] 2017-09-06 02:01
@longsack I just checked, and I forgot to remove blessings from mfcauto. Try running 
`python3.5 -m pip install blessings`
And see if that fixes it. 

I'm replying from my phone, so hopefully that formats right.

**Comment by longsack** [comment] 2017-09-06 02:06
![capture2](https://user-images.githubusercontent.com/31635078/30091196-eed08aa8-927d-11e7-9386-f57fe026d4b6.PNG)
says already satisfied... python3.5 MFCRecorder.py then still throws error no module named '_curses'

**Comment by longsack** [comment] 2017-09-06 02:07
also not sure about the "FileNotFoundError: Errno 2 No such file or directory error as well.
 will keep looking on line for this blasted curses lol

**Comment by beaston02** [comment] 2017-09-06 02:10
That error is a result of getModels not creating the file. Fixing the first should also fix that. 

Try installing the master branch I forked mfcauto.py from. 

https://github.com/ZombieAlex/mfcauto.py/blob/master/README.rst

The command should be in the readme. I made some small changes, but installing from his repo should be fine.

**Comment by longsack** [comment] 2017-09-06 02:15
![capture4](https://user-images.githubusercontent.com/31635078/30091440-3ea05242-927f-11e7-8f09-79cbfa3da498.PNG)

Seems still the curses error see screen from the install you provided in your last reply... thank you by the way for taking the time to assist me on this!!!!!!!!

**Comment by longsack** [comment] 2017-09-06 02:16
is it because it looks like it installed from lib/python2.7?

**Comment by longsack** [comment] 2017-09-06 02:17
i have 3.5 installed, but for whatever reason it seems to want to use 2.7 sometimes, not sure how to remove.

**Comment by beaston02** [comment] 2017-09-06 02:19
Yeah. When you run "pip" it is ran for 2.7. Running "pip3" should run it for 3.5. I generally instruct people to do "python3.5 -m pip" just to be sure they are running the right one, but that's a rather uncommon recommendation and not a normal approach, but it insures you're running the one for python3.5. 

So replace "pip" in the command with "python3.5 -m pip" and it should do it.

**Comment by longsack** [comment] 2017-09-06 02:22
BING -- ALL WORKING!

**Comment by beaston02** [comment] 2017-09-06 02:27
Awesome! Glad to hear it! I'll fix my version of mfcauto, but the original will serve you just fine. A small number of MFCs servers don't allow connections the way we connect to see who's online, so you will get a slightly higher failure rate using his branch, but not enough to be concerned (I ran it for years before I recently made the changes myself). 

Also, I'm happy to help! I'm just here to learn, and each issue is another chance to learn! Let me know if there is anything else. I'm going to close this issue. 

Enjoy!!

**Closed by beaston02** 2017-09-06 02:27 UTC
